version: '3.9'
services:
  puzzle-pirces:
    image: postgres
    restart: always
    container_name: puzzle-pirces
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: